server:
  port: 8002

spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=ture&useSSL=false
    username: root
    password: 951209
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.ga.entity

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 这个地址是和eureka的服务地址一样的
#      ,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka