server:
  port: 8004
spring:
  application:
    name: provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=ture&useSSL=false
    username: root
    password: 951209
  cloud:
    zookeeper:
      connect-string: localhost:2181
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.ga.entity

